In [38]:
import pandas as pd
import numpy as np
data = pd.read_csv("Google-Playstore.csv", encoding="utf-8-sig")
data.head()

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Id,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,com.global.foodpanda.android,Food & Drink,4.4,1258493.0,"10,000,000+",10000000.0,48828081,True,0.00,...,Foodpanda GmbH a subsidiary of Delivery Hero SE,http://foodpanda.com,appsupport@foodpanda.com,"Nov 19, 2013",2020-07-07 00:14:05,Everyone,https://www.foodpanda.sg/contents/privacy.htm,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",com.tripadvisor.tripadvisor,Travel & Local,4.4,1360172.0,"100,000,000+",100000000.0,371284181,True,0.00,...,Tripadvisor,https://www.tripadvisor.com/help,mobilehelp@tripadvisor.com,"Jul 12, 2010",2020-07-02 20:10:48,Everyone,https://www.tripadvisor.com/pages/privacy.html,True,False,False
2,Safeway Delivery & Pick Up,com.safeway.shop,Shopping,4.2,5532.0,"500,000+",500000.0,816102,True,0.00,...,"Albertsons Companies, Inc.",http://www.safeway.com,homeshopping@customerservice.safeway.com,"Sep 5, 2013",2020-07-16 23:21:50,Everyone,http://www.safeway.com/ShopStores/Privacy-Poli...,False,False,False
3,My CookBook Ad-Free,fr.cookbookpro,Food & Drink,4.7,2531.0,"10,000+",10000.0,16171,False,5.99,...,Maadinfo Services,https://www.mycookbook-online.net,support@mycookbook-online.net,"Sep 25, 2011",2020-07-07 12:41:28,Everyone,https://www.mycookbook-android.com/site/privac...,False,False,False
4,Talabat: Food & Grocery Delivery,com.talabat,Food & Drink,4.4,197649.0,"5,000,000+",5000000.0,9218590,True,0.00,...,Talabat,http://www.talabat.com,info@talabat.com,"Jan 19, 2012",2020-07-15 19:21:16,Mature 17+,https://www.talabat.com/kuwait/privacy,True,False,False

In [39]:
data.shape

(603047, 23)

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603047 entries, 0 to 603046
Data columns (total 23 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   App Name           603046 non-null  object
 1   App Id             603047 non-null  object
 2   Category           603047 non-null  object
 3   Rating             599287 non-null  float64
 4   Rating Count       599287 non-null  float64
 5   Installs           602875 non-null  object
 6   Minimum Installs   602875 non-null  float64
 7   Maximum Installs   603047 non-null  int64
 8   Free               603047 non-null  bool
 9   Price              603047 non-null  float64
 10  Currency           602866 non-null  object
 11  Size               603047 non-null  object
 12  Minimum Android    602556 non-null  object
 13  Developer Id       603045 non-null  object
 14  Developer Website  423783 non-null  object
 15  Developer Email    603010 non-null  object
 16  Released           570769 non-null  object
 17  Last Updated       603047 non-null  object
 18  Content Rating     603047 non-null  object
 19  Privacy Policy     517662 non-null  object
 20  Ad Supported       603047 non-null  bool
 21  In App Purchases   603047 non-null  bool
 22  Editors Choice     603047 non-null  bool
dtypes: bool(4), float64(4), int64(1), object(14)
memory usage: 89.7+ MB

In [41]:
data.describe()

,Rating,Rating Count,Minimum Installs,Maximum Installs,Price
count,599287.000000,5.992870e+05,6.028750e+05,6.030470e+05,603047.000000
mean,2.995484,8.627273e+03,4.997939e+05,8.566150e+05,0.248818
std,1.911436,3.467317e+05,2.523102e+07,3.755474e+07,3.392709
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000
25%,0.000000,0.000000e+00,1.000000e+02,4.680000e+02,0.000000
50%,4.000000,2.900000e+01,5.000000e+03,5.034000e+03,0.000000
75%,4.400000,2.560000e+02,1.000000e+04,4.346500e+04,0.000000
max,5.000000,1.170193e+08,5.000000e+09,9.975727e+09,400.000000

In [42]:
data.isnull().sum()

App Name                  1
App Id                    0
Category                  0
Rating                 3760
Rating Count           3760
Installs                172
Minimum Installs        172
Maximum Installs          0
Free                      0
Price                     0
Currency                181
Size                      0
Minimum Android         491
Developer Id              2
Developer Website    179264
Developer Email          37
Released              32278
Last Updated              0
Content Rating            0
Privacy Policy        85385
Ad Supported              0
In App Purchases          0
Editors Choice            0
dtype: int64

### 결측치를 어떻게 다뤄야 하지?
- 결측치가 크고 필요 없을 것 같은 column을 제거하고
- 쓸 column만 빼자

In [43]:
data = data[['App Name', 'Category', 'Rating', 'Rating Count', 'Installs', 'Free', 'Price', 'Size', 'Released', 'Last Updated', 'Ad Supported', 'In App Purchases', 'Editors Choice']]
data.head()

,App Name,Category,Rating,Rating Count,Installs,Free,Price,Size,Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,Food & Drink,4.4,1258493.0,"10,000,000+",True,0.00,21M,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",Travel & Local,4.4,1360172.0,"100,000,000+",True,0.00,Varies with device,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,Shopping,4.2,5532.0,"500,000+",True,0.00,12M,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,Food & Drink,4.7,2531.0,"10,000+",False,5.99,Varies with device,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,Food & Drink,4.4,197649.0,"5,000,000+",True,0.00,Varies with device,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

In [44]:
data.isnull().sum()

App Name                1
Category                0
Rating               3760
Rating Count         3760
Installs              172
Free                    0
Price                   0
Size                    0
Released            32278
Last Updated            0
Ad Supported            0
In App Purchases        0
Editors Choice          0
dtype: int64

## 결측치 제거
### App Name, Rating, Rating Count, Installs, Realeased의 결측치를 어떻게 다루지..?

#### Rating & Rating Count
- median으로 채우기.

In [45]:
data[data['Rating'] == 'NaN']

Empty DataFrame
Columns: [App Name, Category, Rating, Rating Count, Installs, Free, Price, Size, Released, Last Updated, Ad Supported, In App Purchases, Editors Choice]
Index: []

In [46]:
data[data['Rating'].isnull()].head()

,App Name,Category,Rating,Rating Count,Installs,Free,Price,Size,Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
280,Motomoshi - Vehicle Fuel & Expense Tracking,Auto & Vehicles,NaN,NaN,"10,000+",True,0.00,6.8M,"Apr 5, 2019",2020-02-06 12:38:50,True,True,False
409,timr Terminal,Productivity,NaN,NaN,50+,True,0.00,Varies with device,NaN,2019-08-20 18:58:35,False,False,False
1290,PERSUS,Tools,NaN,NaN,10+,True,0.00,Varies with device,NaN,2019-08-16 22:32:32,False,False,False
1390,MusicTime! Music streaming app available on MTN,Music & Audio,NaN,NaN,"500,000+",True,0.00,7.5M,NaN,2020-07-13 13:23:35,False,False,False
1420,KeePassDX Pro,Tools,NaN,NaN,500+,False,5.99,Varies with device,NaN,2020-07-17 13:48:41,False,False,False

In [47]:
values = {'Rating': data['Rating'].median(), 'Rating Count': data['Rating Count'].median()}
data = data.fillna(value=values)

In [48]:
data.isnull().sum()

App Name                1
Category                0
Rating                  0
Rating Count            0
Installs              172
Free                    0
Price                   0
Size                    0
Released            32278
Last Updated            0
Ad Supported            0
In App Purchases        0
Editors Choice          0
dtype: int64

#### App Name
- nan인 게 하나니까 그냥 제거하기.
- 이름이 겹치는 게 있는지 확인하기

In [49]:
name_count = data.groupby('App Name').count()
name_count[name_count['Rating']>1]

Empty DataFrame
Columns: [Category, Rating, Rating Count, Installs, Free, Price, Size, Released, Last Updated, Ad Supported, In App Purchases, Editors Choice]
Index: []

In [50]:
data['App Name'].value_counts()

Numbers - Voice Guide - Speaking        1
Hollywood Bikini Photos App             1
THE GULU Campaign Admin                 1
Isme Azam Ki Barkat                     1
HexaMania Puzzle                        1
                                       ..
Urdu News - Pakistan News               1
Red and Black Leather Keyboard Theme    1
NEI Meetings                            1
Shopping list license                   1
Secret Memo(Free note)                  1
Name: App Name, Length: 603046, dtype: int64

In [51]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603047 entries, 0 to 603046
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   App Name          603046 non-null  object
 1   Category          603047 non-null  object
 2   Rating            603047 non-null  float64
 3   Rating Count      603047 non-null  float64
 4   Installs          602875 non-null  object
 5   Free              603047 non-null  bool
 6   Price             603047 non-null  float64
 7   Size              603047 non-null  object
 8   Released          570769 non-null  object
 9   Last Updated      603047 non-null  object
 10  Ad Supported      603047 non-null  bool
 11  In App Purchases  603047 non-null  bool
 12  Editors Choice    603047 non-null  bool
dtypes: bool(4), float64(3), object(6)
memory usage: 43.7+ MB

In [52]:
data[data['App Name'].isnull()]

,App Name,Category,Rating,Rating Count,Installs,Free,Price,Size,Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
329830,NaN,News & Magazines,2.3,456.0,"50,000+",True,0.0,26M,"Aug 8, 2011",2020-06-24 14:04:49,True,False,False

In [53]:
data = data.drop([329830])
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 603046 entries, 0 to 603046
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   App Name          603046 non-null  object
 1   Category          603046 non-null  object
 2   Rating            603046 non-null  float64
 3   Rating Count      603046 non-null  float64
 4   Installs          602874 non-null  object
 5   Free              603046 non-null  bool
 6   Price             603046 non-null  float64
 7   Size              603046 non-null  object
 8   Released          570768 non-null  object
 9   Last Updated      603046 non-null  object
 10  Ad Supported      603046 non-null  bool
 11  In App Purchases  603046 non-null  bool
 12  Editors Choice    603046 non-null  bool
dtypes: bool(4), float64(3), object(6)
memory usage: 48.3+ MB

In [54]:
data.isnull().sum()

App Name                0
Category                0
Rating                  0
Rating Count            0
Installs              172
Free                    0
Price                   0
Size                    0
Released            32278
Last Updated            0
Ad Supported            0
In App Purchases        0
Editors Choice          0
dtype: int64

### installs와 released는 drop (추후 더 나은 방향으로 수정 예정)
#### data -> data1

In [55]:
data1 = data.copy()
data1 = data1.dropna()

In [56]:
data1.isnull().sum()

App Name            0
Category            0
Rating              0
Rating Count        0
Installs            0
Free                0
Price               0
Size                0
Released            0
Last Updated        0
Ad Supported        0
In App Purchases    0
Editors Choice      0
dtype: int64

In [57]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 570767 entries, 0 to 603046
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   App Name          570767 non-null  object
 1   Category          570767 non-null  object
 2   Rating            570767 non-null  float64
 3   Rating Count      570767 non-null  float64
 4   Installs          570767 non-null  object
 5   Free              570767 non-null  bool
 6   Price             570767 non-null  float64
 7   Size              570767 non-null  object
 8   Released          570767 non-null  object
 9   Last Updated      570767 non-null  object
 10  Ad Supported      570767 non-null  bool
 11  In App Purchases  570767 non-null  bool
 12  Editors Choice    570767 non-null  bool
dtypes: bool(4), float64(3), object(6)
memory usage: 45.7+ MB

### Dtype이 object인 것들 다루기
: installs, size

In [58]:
data1.head()

,App Name,Category,Rating,Rating Count,Installs,Free,Price,Size,Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,Food & Drink,4.4,1258493.0,"10,000,000+",True,0.00,21M,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",Travel & Local,4.4,1360172.0,"100,000,000+",True,0.00,Varies with device,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,Shopping,4.2,5532.0,"500,000+",True,0.00,12M,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,Food & Drink,4.7,2531.0,"10,000+",False,5.99,Varies with device,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,Food & Drink,4.4,197649.0,"5,000,000+",True,0.00,Varies with device,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

#### Installs
- 뒤에 붙은 + 빼고, float로 바꾸기.

In [59]:
data1['Installs'].unique()

array(['10,000,000+', '100,000,000+', '500,000+', '10,000+', '5,000,000+',
       '100,000+', '50,000,000+', '1,000,000+', '50,000+', '500,000,000+',
       '1,000+', '100+', '5,000+', '50+', '500+', '0+', '10+', '5+', '1+',
       '1,000,000,000+', '5,000,000,000+'], dtype=object)

In [60]:
def to_float(row):
    row = row.rstrip('+').replace(',','')
    return float(row)/1000

def devide_1000(row):
    return row/1000
data1['Installs'] = data1['Installs'].apply(to_float)
data1 = data1.rename(columns={'Installs':'Installs(k)', 'Rating Count':'Rating Count(k)'})
data1.head()

,App Name,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size,Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,Food & Drink,4.4,1258493.0,10000.0,True,0.00,21M,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",Travel & Local,4.4,1360172.0,100000.0,True,0.00,Varies with device,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,Shopping,4.2,5532.0,500.0,True,0.00,12M,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,Food & Drink,4.7,2531.0,10.0,False,5.99,Varies with device,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,Food & Drink,4.4,197649.0,5000.0,True,0.00,Varies with device,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

#### size
- M 없애기

In [61]:
data1['Size'].unique().tolist()

['21M',
 'Varies with device',
 '12M',
 '38M',
 '30M',
 '59M',
 '4.9M',
 '11M',
 '25M',
 '9.9M',
 '20M',
 '24M',
 '46M',
 '13M',
 '14M',
 '33M',
 '99M',
 '18M',
 '105M',
 '6.9M',
 '28M',
 '6.1M',
 '22M',
 '52M',
 '5.7M',
 '71M',
 '29M',
 '57M',
 '31M',
 '19M',
 '40M',
 '2.4M',
 '117M',
 '48M',
 '10.0M',
 '5.8M',
 '5.0M',
 '7.8M',
 '4.8M',
 '37M',
 '10M',
 '42M',
 '3.4M',
 '67M',
 '9.0M',
 '35M',
 '102M',
 '17M',
 '15M',
 '4.6M',
 '34M',
 '9.6M',
 '5.6M',
 '6.0M',
 '7.3M',
 '6.4M',
 '86M',
 '45M',
 '77M',
 '26M',
 '7.1M',
 '9.3M',
 '66M',
 '4.3M',
 '2.9M',
 '7.9M',
 '94M',
 '32M',
 '63M',
 '108M',
 '58M',
 '68M',
 '8.8M',
 '3.2M',
 '1.2M',
 '1.6M',
 '43M',
 '2.1M',
 '8.2M',
 '41M',
 '49M',
 '60M',
 '8.4M',
 '16M',
 '53M',
 '9.8M',
 '51M',
 '5.5M',
 '54M',
 '2.2M',
 '2.6M',
 '50M',
 '297k',
 '36M',
 '5.1M',
 '27M',
 '6.5M',
 '4.5M',
 '5.4M',
 '44M',
 '4.2M',
 '8.1M',
 '109M',
 '9.7M',
 '65M',
 '3.6M',
 '16k',
 '3.3M',
 '1.9M',
 '70M',
 '4.4M',
 '9.4M',
 '6.8M',
 '74M',
 '8.7M',
 '4.0M',
 '84M',
 '3.9M',
 '2.5M',
 '2.8M',
 '83k',
 '8.9M',
 '47M',
 '8.5M',
 '4.1M',
 '3.0M',
 '5.9M',
 '6.6M',
 '1.8M',
 '169M',
 '360k',
 '3.7M',
 '8.0M',
 '39M',
 '7.7M',
 '80M',
 '61M',
 '7.4M',
 '114k',
 '90M',
 '5.3M',
 '4.7M',
 '7.6M',
 '92M',
 '23M',
 '1.0M',
 '477k',
 '6.7M',
 '100M',
 '76M',
 '2.3M',
 '643k',
 '3.5M',
 '584k',
 '8.3M',
 '82M',
 '645k',
 '97M',
 '64M',
 '3.8M',
 '2.0M',
 '1.1M',
 '2.7M',
 '7.0M',
 '96M',
 '152M',
 '85M',
 '101M',
 '9.2M',
 '3.1M',
 '1.3M',
 '62M',
 '56M',
 '9.1M',
 '610k',
 '6.3M',
 '6.2M',
 '8.6M',
 '103M',
 '69M',
 '1.7M',
 '1.5M',
 '99k',
 '116M',
 '78M',
 '5.2M',
 '1.4M',
 '55M',
 '93M',
 '79M',
 '81M',
 '580k',
 '72M',
 '110M',
 '644k',
 '83M',
 '581k',
 '633k',
 '373k',
 '130M',
 '9.5M',
 '865k',
 '111M',
 '7.5M',
 '757k',
 '530k',
 '126k',
 '452k',
 '766k',
 '40k',
 '957k',
 '75M',
 '89M',
 '201k',
 '7.2M',
 '127k',
 '82k',
 '14k',
 '164k',
 '955k',
 '210M',
 '121M',
 '73M',
 '651k',
 '128M',
 '180M',
 '916k',
 '87M',
 '31k',
 '43k',
 '568k',
 '807k',
 '95M',
 '209k',
 '619k',
 '113k',
 '146M',
 '442k',
 '387k',
 '25k',
 '144M',
 '283k',
 '187k',
 '582k',
 '604k',
 '572k',
 '148M',
 '505k',
 '162k',
 '555k',
 '598k',
 '92k',
 '98M',
 '104M',
 '151M',
 '137M',
 '129M',
 '113M',
 '91M',
 '703k',
 '134M',
 '309M',
 '112M',
 '119M',
 '157M',
 '138M',
 '216k',
 '672k',
 '118M',
 '88M',
 '126M',
 '139M',
 '123M',
 '196M',
 '702k',
 '564k',
 '208M',
 '350k',
 '888k',
 '197k',
 '879k',
 '730k',
 '828k',
 '140M',
 '437k',
 '470k',
 '253M',
 '124M',
 '773k',
 '620k',
 '174k',
 '758k',
 '947k',
 '53k',
 '155M',
 '1,016k',
 '85k',
 '33k',
 '61k',
 '478k',
 '959k',
 '35k',
 '684k',
 '528k',
 '216M',
 '713k',
 '642k',
 '136M',
 '154M',
 '695k',
 '222M',
 '122M',
 '143M',
 '132M',
 '120M',
 '153M',
 '214M',
 '133M',
 '570k',
 '107M',
 '135M',
 '522k',
 '280k',
 '267k',
 '158k',
 '106M',
 '576k',
 '155k',
 '287k',
 '398k',
 '798k',
 '659k',
 '37k',
 '97k',
 '968k',
 '115k',
 '409k',
 '925k',
 '429k',
 '205k',
 '673k',
 '362k',
 '779k',
 '44k',
 '279k',
 '885k',
 '834k',
 '231k',
 '523k',
 '77k',
 '411k',
 '115M',
 '266k',
 '252k',
 '24k',
 '395k',
 '356k',
 '114M',
 '364k',
 '822k',
 '558k',
 '592k',
 '711k',
 '145M',
 '704k',
 '259k',
 '191k',
 '131M',
 '420k',
 '914k',
 '162M',
 '491k',
 '402k',
 '453k',
 '368k',
 '559k',
 '120k',
 '38k',
 '742k',
 '937k',
 '436k',
 '207M',
 '246k',
 '1,001k',
 '467k',
 '693k',
 '434k',
 '1,017k',
 '989k',
 '638k',
 '718k',
 '321k',
 '329k',
 '678k',
 '637k',
 '179k',
 '665k',
 '814k',
 '215k',
 '281k',
 '203k',
 '270k',
 '996k',
 '326k',
 '357k',
 '262k',
 '1,012k',
 '48k',
 '325k',
 '900k',
 '178M',
 '974k',
 '640k',
 '856k',
 '687k',
 '425k',
 '147M',
 '26k',
 '397k',
 '607k',
 '160M',
 '175M',
 '142M',
 '164M',
 '149M',
 '302k',
 '70k',
 '98k',
 '1,010k',
 '336k',
 '887k',
 '972k',
 '187M',
 '193k',
 '218k',
 '953k',
 '691k',
 '361k',
 '630k',
 '951k',
 '762k',
 '324k',
 '391k',
 '135k',
 '433k',
 '290k',
 '589k',
 '754k',
 '227M',
 '21k',
 '971k',
 '820k',
 '188M',
 '260k',
 '825k',
 '824k',
 '152k',
 '708k',
 '833k',
 '755k',
 '774k',
 '721k',
 '577k',
 '699k',
 '727k',
 '776k',
 '602k',
 '689k',
 '385k',
 '854k',
 '593k',
 '902k',
 '518k',
 '871k',
 '836k',
 '112k',
 '533k',
 '421k',
 '565k',
 '694k',
 '28k',
 '521k',
 '763k',
 '100k',
 '967k',
 '404k',
 '300k',
 '22k',
 '657k',
 '408k',
 '17k',
 '930k',
 '821k',
 '439k',
 '127M',
 '125M',
 '225M',
 '1,014k',
 '105k',
 '108k',
 '366k',
 '224k',
 '352k',
 '526k',
 '173k',
 '125k',
 '459k',
 '493k',
 '464k',
 '394k',
 '36k',
 '141M',
 '386k',
 '484k',
 '220M',
 '804k',
 '618k',
 '870k',
 '69k',
 '1,006k',
 '847k',
 '863k',
 '32k',
 '78k',
 '918k',
 '622k',
 '712k',
 '850k',
 '15k',
 '1,007k',
 '550k',
 '802k',
 '309k',
 '160k',
 '808k',
 '150M',
 '606k',
 '733k',
 '141k',
 '79k',
 '677k',
 '183M',
 '86k',
 '123k',
 '261k',
 '629k',
 '941k',
 '288k',
 '183k',
 '495k',
 '238k',
 '13k',
 '8.9k',
 '960k',
 '49k',
 '811k',
 '12k',
 '30k',
 '66k',
 '255k',
 '560k',
 '219k',
 '892k',
 '894k',
 '529k',
 '573k',
 '943k',
 '537k',
 '525k',
 '527k',
 '552k',
 '91k',
 '535k',
 '107k',
 '855k',
 '872k',
 '519k',
 '492k',
 '706k',
 '373M',
 '139k',
 '168M',
 '973k',
 '457k',
 '605k',
 '334k',
 '167M',
 '285k',
 '1,015k',
 '232k',
 '379k',
 '161M',
 '177k',
 '510k',
 '365k',
 '206k',
 '242k',
 '392k',
 '138k',
 '156k',
 '330k',
 '415k',
 '188k',
 '401k',
 '376k',
 '372k',
 '313k',
 '186k',
 '426k',
 '575k',
 '623k',
 '199k',
 '237k',
 '359k',
 '469k',
 '1,013k',
 '367k',
 '148k',
 '144k',
 '641k',
 '906k',
 '431k',
 '29k',
 '27k',
 '153k',
 '217k',
 '471k',
 '504k',
 '768k',
 '675k',
 '688k',
 '388k',
 '407k',
 '789k',
 '378k',
 '939k',
 '843k',
 '966k',
 '932k',
 '948k',
 '961k',
 '908k',
 '840k',
 '862k',
 '150k',
 '767k',
 '202k',
 '719k',
 '543k',
 '841k',
 '929k',
 '137k',
 '676k',
 '375k',
 '679k',
 '346k',
 '23k',
 '823k',
 '832k',
 '479k',
 '868k',
 '701k',
 '849k',
 '857k',
 '946k',
 '934k',
 '910k',
 '542k',
 '792k',
 '969k',
 '490k',
 '455k',
 '940k',
 '1,021k',
 '384k',
 '213k',
 '852k',
 '333k',
 '845k',
 '369k',
 '342k',
 '339k',
 '20k',
 '597k',
 '583k',
 '788k',
 '636k',
 '904k',
 '1,003k',
 '317k',
 '447k',
 '268k',
 '664k',
 '723k',
 '650k',
 '655k',
 '171M',
 '158M',
 '800k',
 '230k',
 '95k',
 '72k',
 '999k',
 '705k',
 '994k',
 '132k',
 '680k',
 '46k',
 '6.1k',
 '233k',
 '756k',
 '740k',
 '988k',
 '506k',
 '601k',
 '944k',
 '194M',
 '498k',
 '976k',
 '963k',
 '403k',
 '990k',
 '282k',
 '247k',
 '245k',
 '569k',
 '448k',
 '915k',
 '514k',
 '222k',
 '503k',
 '410k',
 '413k',
 '393k',
 '970k',
 '1,008k',
 '185k',
 '877k',
 '917k',
 '716k',
 '748k',
 '1,020k',
 '890k',
 '818k',
 '156M',
 '229k',
 '347M',
 '654k',
 '263k',
 '743k',
 '34k',
 '954k',
 '165k',
 '191M',
 '192M',
 '193M',
 '190M',
 '195M',
 '726k',
 '273k',
 '74k',
 '272k',
 '826k',
 '661k',
 '316k',
 '795k',
 '819k',
 '615k',
 '318k',
 '151k',
 '81k',
 '119k',
 '600k',
 '45k',
 '178k',
 '759k',
 '806k',
 '210k',
 '129k',
 '194k',
 '145k',
 '41k',
 '243k',
 '305k',
 '571k',
 '880k',
 '752k',
 '109k',
 '62k',
 '149k',
 '627k',
 '39k',
 '487k',
 '52k',
 '89k',
 '250k',
 '977k',
 '96k',
 '84k',
 '251k',
 '291M',
 '390k',
 '893k',
 '184k',
 '8.4k',
 '539k',
 '327k',
 '166k',
 '236k',
 '307k',
 '595k',
 '590k',
 '591k',
 '728k',
 '991k',
 '964k',
 '785k',
 '554k',
 '190k',
 '87k',
 '76k',
 '214k',
 '586k',
 '899k',
 '343k',
 '509k',
 '671k',
 '1,023k',
 '831k',
 '473k',
 '341k',
 '839k',
 '353k',
 '765k',
 '866k',
 '462k',
 '998k',
 '738k',
 '256k',
 '240k',
 '128k',
 '234k',
 '225k',
 '117k',
 '992k',
 '370k',
 '796k',
 '19k',
 '881k',
 '935k',
 '631k',
 '753k',
 '340k',
 '797k',
 '171k',
 '816k',
 '896k',
 '978k',
 '485k',
 '658k',
 '667k',
 '720k',
 '707k',
 '628k',
 '731k',
 '632k',
 '616k',
 '764k',
 '668k',
 '609k',
 '781k',
 '710k',
 '47k',
 '163M',
 '842k',
 '130k',
 '301k',
 '211k',
 '147k',
 '227k',
 '63k',
 '474k',
 '212k',
 '64k',
 '104k',
 '207k',
 '486k',
 '320k',
 '382k',
 '93k',
 '337k',
 '94k',
 '55k',
 '846k',
 '805k',
 '874k',
 '540k',
 '907k',
 '106k',
 '136k',
 '1,024k',
 '1,022k',
 '244k',
 '926k',
 '924k',
 '175k',
 '181k',
 '803k',
 '481k',
 '697k',
 '67k',
 '206M',
 '520k',
 '717k',
 '167k',
 '275k',
 '244M',
 '223k',
 '111k',
 '1,009k',
 '901k',
 '729k',
 '844k',
 '987k',
 '815k',
 '772k',
 '265k',
 '494k',
 '189k',
 '791k',
 '635k',
 '338k',
 '308k',
 '483k',
 '371k',
 '423k',
 '541k',
 '458k',
 '335k',
 '312k',
 '775k',
 '140k',
 '734k',
 '65k',
 '794k',
 '588k',
 '176M',
 '116k',
 '80k',
 '965k',
 '500k',
 '952k',
 '709k',
 '323k',
 '412k',
 '405k',
 '399k',
 '669k',
 '594k',
 '349k',
 '562k',
 '563k',
 '419k',
 '441k',
 '480k',
 '345k',
 '578k',
 '737k',
 '612k',
 '683k',
 '406k',
 '233M',
 '354M',
 '291k',
 '385M',
 '454k',
 '276k',
 '903k',
 '1,000k',
 '545k',
 '1,005k',
 '239k',
 '10k',
 '372M',
 '264k',
 '891k',
 '311k',
 '374k',
 '532k',
 '400k',
 '299k',
 '284k',
 '286k',
 '347k',
 '979k',
 '905k',
 '652k',
 '445k',
 '476k',
 '548k',
 ...]

In [62]:
data1['Size'][data1['Size']=='Varies with device'].count()

21239

In [63]:
data1['Size'][data1['Size']=='Varies with device'] = np.nan
data1.head()

<ipython-input-63-2fe94186afc3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['Size'][data1['Size']=='Varies with device'] = np.nan

,App Name,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size,Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,Food & Drink,4.4,1258493.0,10000.0,True,0.00,21M,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",Travel & Local,4.4,1360172.0,100000.0,True,0.00,NaN,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,Shopping,4.2,5532.0,500.0,True,0.00,12M,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,Food & Drink,4.7,2531.0,10.0,False,5.99,NaN,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,Food & Drink,4.4,197649.0,5000.0,True,0.00,NaN,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

In [64]:
data1['Size'].unique().tolist()

['21M',
 nan,
 '12M',
 '38M',
 '30M',
 '59M',
 '4.9M',
 '11M',
 '25M',
 '9.9M',
 '20M',
 '24M',
 '46M',
 '13M',
 '14M',
 '33M',
 '99M',
 '18M',
 '105M',
 '6.9M',
 '28M',
 '6.1M',
 '22M',
 '52M',
 '5.7M',
 '71M',
 '29M',
 '57M',
 '31M',
 '19M',
 '40M',
 '2.4M',
 '117M',
 '48M',
 '10.0M',
 '5.8M',
 '5.0M',
 '7.8M',
 '4.8M',
 '37M',
 '10M',
 '42M',
 '3.4M',
 '67M',
 '9.0M',
 '35M',
 '102M',
 '17M',
 '15M',
 '4.6M',
 '34M',
 '9.6M',
 '5.6M',
 '6.0M',
 '7.3M',
 '6.4M',
 '86M',
 '45M',
 '77M',
 '26M',
 '7.1M',
 '9.3M',
 '66M',
 '4.3M',
 '2.9M',
 '7.9M',
 '94M',
 '32M',
 '63M',
 '108M',
 '58M',
 '68M',
 '8.8M',
 '3.2M',
 '1.2M',
 '1.6M',
 '43M',
 '2.1M',
 '8.2M',
 '41M',
 '49M',
 '60M',
 '8.4M',
 '16M',
 '53M',
 '9.8M',
 '51M',
 '5.5M',
 '54M',
 '2.2M',
 '2.6M',
 '50M',
 '297k',
 '36M',
 '5.1M',
 '27M',
 '6.5M',
 '4.5M',
 '5.4M',
 '44M',
 '4.2M',
 '8.1M',
 '109M',
 '9.7M',
 '65M',
 '3.6M',
 '16k',
 '3.3M',
 '1.9M',
 '70M',
 '4.4M',
 '9.4M',
 '6.8M',
 '74M',
 '8.7M',
 '4.0M',
 '84M',
 '3.9M',
 '2.5M',
 '2.8M',
 '83k',
 '8.9M',
 '47M',
 '8.5M',
 '4.1M',
 '3.0M',
 '5.9M',
 '6.6M',
 '1.8M',
 '169M',
 '360k',
 '3.7M',
 '8.0M',
 '39M',
 '7.7M',
 '80M',
 '61M',
 '7.4M',
 '114k',
 '90M',
 '5.3M',
 '4.7M',
 '7.6M',
 '92M',
 '23M',
 '1.0M',
 '477k',
 '6.7M',
 '100M',
 '76M',
 '2.3M',
 '643k',
 '3.5M',
 '584k',
 '8.3M',
 '82M',
 '645k',
 '97M',
 '64M',
 '3.8M',
 '2.0M',
 '1.1M',
 '2.7M',
 '7.0M',
 '96M',
 '152M',
 '85M',
 '101M',
 '9.2M',
 '3.1M',
 '1.3M',
 '62M',
 '56M',
 '9.1M',
 '610k',
 '6.3M',
 '6.2M',
 '8.6M',
 '103M',
 '69M',
 '1.7M',
 '1.5M',
 '99k',
 '116M',
 '78M',
 '5.2M',
 '1.4M',
 '55M',
 '93M',
 '79M',
 '81M',
 '580k',
 '72M',
 '110M',
 '644k',
 '83M',
 '581k',
 '633k',
 '373k',
 '130M',
 '9.5M',
 '865k',
 '111M',
 '7.5M',
 '757k',
 '530k',
 '126k',
 '452k',
 '766k',
 '40k',
 '957k',
 '75M',
 '89M',
 '201k',
 '7.2M',
 '127k',
 '82k',
 '14k',
 '164k',
 '955k',
 '210M',
 '121M',
 '73M',
 '651k',
 '128M',
 '180M',
 '916k',
 '87M',
 '31k',
 '43k',
 '568k',
 '807k',
 '95M',
 '209k',
 '619k',
 '113k',
 '146M',
 '442k',
 '387k',
 '25k',
 '144M',
 '283k',
 '187k',
 '582k',
 '604k',
 '572k',
 '148M',
 '505k',
 '162k',
 '555k',
 '598k',
 '92k',
 '98M',
 '104M',
 '151M',
 '137M',
 '129M',
 '113M',
 '91M',
 '703k',
 '134M',
 '309M',
 '112M',
 '119M',
 '157M',
 '138M',
 '216k',
 '672k',
 '118M',
 '88M',
 '126M',
 '139M',
 '123M',
 '196M',
 '702k',
 '564k',
 '208M',
 '350k',
 '888k',
 '197k',
 '879k',
 '730k',
 '828k',
 '140M',
 '437k',
 '470k',
 '253M',
 '124M',
 '773k',
 '620k',
 '174k',
 '758k',
 '947k',
 '53k',
 '155M',
 '1,016k',
 '85k',
 '33k',
 '61k',
 '478k',
 '959k',
 '35k',
 '684k',
 '528k',
 '216M',
 '713k',
 '642k',
 '136M',
 '154M',
 '695k',
 '222M',
 '122M',
 '143M',
 '132M',
 '120M',
 '153M',
 '214M',
 '133M',
 '570k',
 '107M',
 '135M',
 '522k',
 '280k',
 '267k',
 '158k',
 '106M',
 '576k',
 '155k',
 '287k',
 '398k',
 '798k',
 '659k',
 '37k',
 '97k',
 '968k',
 '115k',
 '409k',
 '925k',
 '429k',
 '205k',
 '673k',
 '362k',
 '779k',
 '44k',
 '279k',
 '885k',
 '834k',
 '231k',
 '523k',
 '77k',
 '411k',
 '115M',
 '266k',
 '252k',
 '24k',
 '395k',
 '356k',
 '114M',
 '364k',
 '822k',
 '558k',
 '592k',
 '711k',
 '145M',
 '704k',
 '259k',
 '191k',
 '131M',
 '420k',
 '914k',
 '162M',
 '491k',
 '402k',
 '453k',
 '368k',
 '559k',
 '120k',
 '38k',
 '742k',
 '937k',
 '436k',
 '207M',
 '246k',
 '1,001k',
 '467k',
 '693k',
 '434k',
 '1,017k',
 '989k',
 '638k',
 '718k',
 '321k',
 '329k',
 '678k',
 '637k',
 '179k',
 '665k',
 '814k',
 '215k',
 '281k',
 '203k',
 '270k',
 '996k',
 '326k',
 '357k',
 '262k',
 '1,012k',
 '48k',
 '325k',
 '900k',
 '178M',
 '974k',
 '640k',
 '856k',
 '687k',
 '425k',
 '147M',
 '26k',
 '397k',
 '607k',
 '160M',
 '175M',
 '142M',
 '164M',
 '149M',
 '302k',
 '70k',
 '98k',
 '1,010k',
 '336k',
 '887k',
 '972k',
 '187M',
 '193k',
 '218k',
 '953k',
 '691k',
 '361k',
 '630k',
 '951k',
 '762k',
 '324k',
 '391k',
 '135k',
 '433k',
 '290k',
 '589k',
 '754k',
 '227M',
 '21k',
 '971k',
 '820k',
 '188M',
 '260k',
 '825k',
 '824k',
 '152k',
 '708k',
 '833k',
 '755k',
 '774k',
 '721k',
 '577k',
 '699k',
 '727k',
 '776k',
 '602k',
 '689k',
 '385k',
 '854k',
 '593k',
 '902k',
 '518k',
 '871k',
 '836k',
 '112k',
 '533k',
 '421k',
 '565k',
 '694k',
 '28k',
 '521k',
 '763k',
 '100k',
 '967k',
 '404k',
 '300k',
 '22k',
 '657k',
 '408k',
 '17k',
 '930k',
 '821k',
 '439k',
 '127M',
 '125M',
 '225M',
 '1,014k',
 '105k',
 '108k',
 '366k',
 '224k',
 '352k',
 '526k',
 '173k',
 '125k',
 '459k',
 '493k',
 '464k',
 '394k',
 '36k',
 '141M',
 '386k',
 '484k',
 '220M',
 '804k',
 '618k',
 '870k',
 '69k',
 '1,006k',
 '847k',
 '863k',
 '32k',
 '78k',
 '918k',
 '622k',
 '712k',
 '850k',
 '15k',
 '1,007k',
 '550k',
 '802k',
 '309k',
 '160k',
 '808k',
 '150M',
 '606k',
 '733k',
 '141k',
 '79k',
 '677k',
 '183M',
 '86k',
 '123k',
 '261k',
 '629k',
 '941k',
 '288k',
 '183k',
 '495k',
 '238k',
 '13k',
 '8.9k',
 '960k',
 '49k',
 '811k',
 '12k',
 '30k',
 '66k',
 '255k',
 '560k',
 '219k',
 '892k',
 '894k',
 '529k',
 '573k',
 '943k',
 '537k',
 '525k',
 '527k',
 '552k',
 '91k',
 '535k',
 '107k',
 '855k',
 '872k',
 '519k',
 '492k',
 '706k',
 '373M',
 '139k',
 '168M',
 '973k',
 '457k',
 '605k',
 '334k',
 '167M',
 '285k',
 '1,015k',
 '232k',
 '379k',
 '161M',
 '177k',
 '510k',
 '365k',
 '206k',
 '242k',
 '392k',
 '138k',
 '156k',
 '330k',
 '415k',
 '188k',
 '401k',
 '376k',
 '372k',
 '313k',
 '186k',
 '426k',
 '575k',
 '623k',
 '199k',
 '237k',
 '359k',
 '469k',
 '1,013k',
 '367k',
 '148k',
 '144k',
 '641k',
 '906k',
 '431k',
 '29k',
 '27k',
 '153k',
 '217k',
 '471k',
 '504k',
 '768k',
 '675k',
 '688k',
 '388k',
 '407k',
 '789k',
 '378k',
 '939k',
 '843k',
 '966k',
 '932k',
 '948k',
 '961k',
 '908k',
 '840k',
 '862k',
 '150k',
 '767k',
 '202k',
 '719k',
 '543k',
 '841k',
 '929k',
 '137k',
 '676k',
 '375k',
 '679k',
 '346k',
 '23k',
 '823k',
 '832k',
 '479k',
 '868k',
 '701k',
 '849k',
 '857k',
 '946k',
 '934k',
 '910k',
 '542k',
 '792k',
 '969k',
 '490k',
 '455k',
 '940k',
 '1,021k',
 '384k',
 '213k',
 '852k',
 '333k',
 '845k',
 '369k',
 '342k',
 '339k',
 '20k',
 '597k',
 '583k',
 '788k',
 '636k',
 '904k',
 '1,003k',
 '317k',
 '447k',
 '268k',
 '664k',
 '723k',
 '650k',
 '655k',
 '171M',
 '158M',
 '800k',
 '230k',
 '95k',
 '72k',
 '999k',
 '705k',
 '994k',
 '132k',
 '680k',
 '46k',
 '6.1k',
 '233k',
 '756k',
 '740k',
 '988k',
 '506k',
 '601k',
 '944k',
 '194M',
 '498k',
 '976k',
 '963k',
 '403k',
 '990k',
 '282k',
 '247k',
 '245k',
 '569k',
 '448k',
 '915k',
 '514k',
 '222k',
 '503k',
 '410k',
 '413k',
 '393k',
 '970k',
 '1,008k',
 '185k',
 '877k',
 '917k',
 '716k',
 '748k',
 '1,020k',
 '890k',
 '818k',
 '156M',
 '229k',
 '347M',
 '654k',
 '263k',
 '743k',
 '34k',
 '954k',
 '165k',
 '191M',
 '192M',
 '193M',
 '190M',
 '195M',
 '726k',
 '273k',
 '74k',
 '272k',
 '826k',
 '661k',
 '316k',
 '795k',
 '819k',
 '615k',
 '318k',
 '151k',
 '81k',
 '119k',
 '600k',
 '45k',
 '178k',
 '759k',
 '806k',
 '210k',
 '129k',
 '194k',
 '145k',
 '41k',
 '243k',
 '305k',
 '571k',
 '880k',
 '752k',
 '109k',
 '62k',
 '149k',
 '627k',
 '39k',
 '487k',
 '52k',
 '89k',
 '250k',
 '977k',
 '96k',
 '84k',
 '251k',
 '291M',
 '390k',
 '893k',
 '184k',
 '8.4k',
 '539k',
 '327k',
 '166k',
 '236k',
 '307k',
 '595k',
 '590k',
 '591k',
 '728k',
 '991k',
 '964k',
 '785k',
 '554k',
 '190k',
 '87k',
 '76k',
 '214k',
 '586k',
 '899k',
 '343k',
 '509k',
 '671k',
 '1,023k',
 '831k',
 '473k',
 '341k',
 '839k',
 '353k',
 '765k',
 '866k',
 '462k',
 '998k',
 '738k',
 '256k',
 '240k',
 '128k',
 '234k',
 '225k',
 '117k',
 '992k',
 '370k',
 '796k',
 '19k',
 '881k',
 '935k',
 '631k',
 '753k',
 '340k',
 '797k',
 '171k',
 '816k',
 '896k',
 '978k',
 '485k',
 '658k',
 '667k',
 '720k',
 '707k',
 '628k',
 '731k',
 '632k',
 '616k',
 '764k',
 '668k',
 '609k',
 '781k',
 '710k',
 '47k',
 '163M',
 '842k',
 '130k',
 '301k',
 '211k',
 '147k',
 '227k',
 '63k',
 '474k',
 '212k',
 '64k',
 '104k',
 '207k',
 '486k',
 '320k',
 '382k',
 '93k',
 '337k',
 '94k',
 '55k',
 '846k',
 '805k',
 '874k',
 '540k',
 '907k',
 '106k',
 '136k',
 '1,024k',
 '1,022k',
 '244k',
 '926k',
 '924k',
 '175k',
 '181k',
 '803k',
 '481k',
 '697k',
 '67k',
 '206M',
 '520k',
 '717k',
 '167k',
 '275k',
 '244M',
 '223k',
 '111k',
 '1,009k',
 '901k',
 '729k',
 '844k',
 '987k',
 '815k',
 '772k',
 '265k',
 '494k',
 '189k',
 '791k',
 '635k',
 '338k',
 '308k',
 '483k',
 '371k',
 '423k',
 '541k',
 '458k',
 '335k',
 '312k',
 '775k',
 '140k',
 '734k',
 '65k',
 '794k',
 '588k',
 '176M',
 '116k',
 '80k',
 '965k',
 '500k',
 '952k',
 '709k',
 '323k',
 '412k',
 '405k',
 '399k',
 '669k',
 '594k',
 '349k',
 '562k',
 '563k',
 '419k',
 '441k',
 '480k',
 '345k',
 '578k',
 '737k',
 '612k',
 '683k',
 '406k',
 '233M',
 '354M',
 '291k',
 '385M',
 '454k',
 '276k',
 '903k',
 '1,000k',
 '545k',
 '1,005k',
 '239k',
 '10k',
 '372M',
 '264k',
 '891k',
 '311k',
 '374k',
 '532k',
 '400k',
 '299k',
 '284k',
 '286k',
 '347k',
 '979k',
 '905k',
 '652k',
 '445k',
 '476k',
 '548k',
 ...]

In [65]:
data1['Size'][(data['Size'].str[-1] != 'k') & (data['Size'].str[-1] != 'M')]

1         NaN
3         NaN
4         NaN
9         NaN
11        NaN
         ...
602433    NaN
602457    NaN
602553    NaN
602664    NaN
602867    NaN
Name: Size, Length: 21239, dtype: object

In [66]:
def k_to_m(row):
    row = str(row).replace(',','')
    if row[-1] == 'k':
        row = float(row[:-1])/1000
    elif row[-1] == 'M':
        row = row[:-1]
    return float(row)

In [67]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 570767 entries, 0 to 603046
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   App Name          570767 non-null  object
 1   Category          570767 non-null  object
 2   Rating            570767 non-null  float64
 3   Rating Count(k)   570767 non-null  float64
 4   Installs(k)       570767 non-null  float64
 5   Free              570767 non-null  bool
 6   Price             570767 non-null  float64
 7   Size              549528 non-null  object
 8   Released          570767 non-null  object
 9   Last Updated      570767 non-null  object
 10  Ad Supported      570767 non-null  bool
 11  In App Purchases  570767 non-null  bool
 12  Editors Choice    570767 non-null  bool
dtypes: bool(4), float64(4), object(5)
memory usage: 45.7+ MB

k -> 1000
m -> 1000000
k * 1000

In [68]:
data1['Size'] = data1['Size'].apply(k_to_m)

In [69]:
data1 = data1.rename(columns={'Size':'Size(M)'})
data1.head()

,App Name,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size(M),Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,Food & Drink,4.4,1258493.0,10000.0,True,0.00,21.0,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",Travel & Local,4.4,1360172.0,100000.0,True,0.00,NaN,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,Shopping,4.2,5532.0,500.0,True,0.00,12.0,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,Food & Drink,4.7,2531.0,10.0,False,5.99,NaN,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,Food & Drink,4.4,197649.0,5000.0,True,0.00,NaN,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

In [70]:
data1['Size(M)'].median()

9.0

#### NaN size는 중간값으로 넣었음.. (이만개 정도 돼서...)

In [71]:
data1['Size(M)'] = data1['Size(M)'].fillna(data1['Size(M)'].median())

In [72]:
data1['Size(M)'].isnull().sum()

0

### 카테고리

In [73]:
data1.head()

,App Name,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size(M),Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,Food & Drink,4.4,1258493.0,10000.0,True,0.00,21.0,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",Travel & Local,4.4,1360172.0,100000.0,True,0.00,9.0,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,Shopping,4.2,5532.0,500.0,True,0.00,12.0,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,Food & Drink,4.7,2531.0,10.0,False,5.99,9.0,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,Food & Drink,4.4,197649.0,5000.0,True,0.00,9.0,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

In [74]:
data1['Category'].unique()

array(['Food & Drink', 'Travel & Local', 'Shopping', 'Business', 'Tools',
       'News & Magazines', 'Music', 'Entertainment', 'Productivity',
       'Maps & Navigation', 'Lifestyle', 'Health & Fitness',
       'Music & Audio', 'Finance', 'Books & Reference', 'Social',
       'Medical', 'Education', 'Sports', 'Weather', 'Communication',
       'Board', 'Puzzle', 'Casual', 'Card', 'Simulation',
       'Auto & Vehicles', 'Events', 'Strategy', 'Action', 'House & Home',
       'Personalization', 'Photography', 'Video Players & Editors',
       'Adventure', 'Educational', 'Word', 'Parenting', 'Beauty',
       'Libraries & Demo', 'Art & Design', 'Trivia', 'Casino', 'Arcade',
       'Role Playing', 'Racing', 'Comics', 'Dating'], dtype=object)

In [75]:
data1['Category'].value_counts()

Education                  72633
Books & Reference          46615
Music & Audio              39548
Entertainment              37783
Tools                      36106
Lifestyle                  32880
Personalization            27135
Business                   24501
Health & Fitness           18296
Productivity               17999
Finance                    17353
Travel & Local             16023
News & Magazines           14537
Sports                     12764
Shopping                   12691
Photography                11790
Food & Drink               11347
Communication              10839
Puzzle                     10599
Social                      8735
Maps & Navigation           7580
Medical                     7524
Casual                      7366
Arcade                      6158
Educational                 5791
Simulation                  4622
Action                      4097
Auto & Vehicles             4046
Video Players & Editors     3973
Art & Design                3754
Adventure                   3363
Role Playing                3094
Beauty                      2679
Word                        2675
Strategy                    2436
Weather                     2419
Board                       2347
Card                        2289
House & Home                2278
Events                      2261
Trivia                      2056
Racing                      1869
Libraries & Demo            1415
Parenting                   1173
Comics                       978
Casino                       853
Dating                       822
Music                        675
Name: Category, dtype: int64

In [76]:
category_li = data1['Category'].unique().tolist()

In [77]:
category_li

['Food & Drink',
 'Travel & Local',
 'Shopping',
 'Business',
 'Tools',
 'News & Magazines',
 'Music',
 'Entertainment',
 'Productivity',
 'Maps & Navigation',
 'Lifestyle',
 'Health & Fitness',
 'Music & Audio',
 'Finance',
 'Books & Reference',
 'Social',
 'Medical',
 'Education',
 'Sports',
 'Weather',
 'Communication',
 'Board',
 'Puzzle',
 'Casual',
 'Card',
 'Simulation',
 'Auto & Vehicles',
 'Events',
 'Strategy',
 'Action',
 'House & Home',
 'Personalization',
 'Photography',
 'Video Players & Editors',
 'Adventure',
 'Educational',
 'Word',
 'Parenting',
 'Beauty',
 'Libraries & Demo',
 'Art & Design',
 'Trivia',
 'Casino',
 'Arcade',
 'Role Playing',
 'Racing',
 'Comics',
 'Dating']

In [78]:
category_dict = {}
for index, category in enumerate(category_li):
    category_dict[category] = index
category_dict

{'Food & Drink': 0,
 'Travel & Local': 1,
 'Shopping': 2,
 'Business': 3,
 'Tools': 4,
 'News & Magazines': 5,
 'Music': 6,
 'Entertainment': 7,
 'Productivity': 8,
 'Maps & Navigation': 9,
 'Lifestyle': 10,
 'Health & Fitness': 11,
 'Music & Audio': 12,
 'Finance': 13,
 'Books & Reference': 14,
 'Social': 15,
 'Medical': 16,
 'Education': 17,
 'Sports': 18,
 'Weather': 19,
 'Communication': 20,
 'Board': 21,
 'Puzzle': 22,
 'Casual': 23,
 'Card': 24,
 'Simulation': 25,
 'Auto & Vehicles': 26,
 'Events': 27,
 'Strategy': 28,
 'Action': 29,
 'House & Home': 30,
 'Personalization': 31,
 'Photography': 32,
 'Video Players & Editors': 33,
 'Adventure': 34,
 'Educational': 35,
 'Word': 36,
 'Parenting': 37,
 'Beauty': 38,
 'Libraries & Demo': 39,
 'Art & Design': 40,
 'Trivia': 41,
 'Casino': 42,
 'Arcade': 43,
 'Role Playing': 44,
 'Racing': 45,
 'Comics': 46,
 'Dating': 47}

In [79]:
def category_to_float(row):
    row = category_dict[row]
    return row

In [80]:
data1['Category'] = data1['Category'].apply(category_to_float)
data1.head()

,App Name,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size(M),Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,0,4.4,1258493.0,10000.0,True,0.00,21.0,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",1,4.4,1360172.0,100000.0,True,0.00,9.0,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,2,4.2,5532.0,500.0,True,0.00,12.0,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,0,4.7,2531.0,10.0,False,5.99,9.0,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,0,4.4,197649.0,5000.0,True,0.00,9.0,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

### boolean을 0/1로

In [81]:
data1.head()

,App Name,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size(M),Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,0,4.4,1258493.0,10000.0,True,0.00,21.0,"Nov 19, 2013",2020-07-07 00:14:05,False,False,False
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",1,4.4,1360172.0,100000.0,True,0.00,9.0,"Jul 12, 2010",2020-07-02 20:10:48,True,False,False
2,Safeway Delivery & Pick Up,2,4.2,5532.0,500.0,True,0.00,12.0,"Sep 5, 2013",2020-07-16 23:21:50,False,False,False
3,My CookBook Ad-Free,0,4.7,2531.0,10.0,False,5.99,9.0,"Sep 25, 2011",2020-07-07 12:41:28,False,False,False
4,Talabat: Food & Grocery Delivery,0,4.4,197649.0,5000.0,True,0.00,9.0,"Jan 19, 2012",2020-07-15 19:21:16,True,False,False

In [82]:
def bool_to_int(row):
    if row:
        row = 1
    else:
        row = 0
    return row

In [87]:
data1['Ad Supported'] = data1['Ad Supported'].apply(bool_to_int)
data1['In App Purchases'] = data1['In App Purchases'].apply(bool_to_int)
data1['Editors Choice'] = data1['Editors Choice'].apply(bool_to_int)
data1['Free'] = data1['Free'].apply(bool_to_int)

In [88]:
data1.head()

,App Name,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size(M),Released,Last Updated,Ad Supported,In App Purchases,Editors Choice
0,foodpanda - Local Food & Grocery Delivery,0,4.4,1258493.0,10000.0,1,0.00,21.0,"Nov 19, 2013",2020-07-07 00:14:05,0,0,0
1,"Tripadvisor Hotel, Flight & Restaurant Bookings",1,4.4,1360172.0,100000.0,1,0.00,9.0,"Jul 12, 2010",2020-07-02 20:10:48,1,0,0
2,Safeway Delivery & Pick Up,2,4.2,5532.0,500.0,1,0.00,12.0,"Sep 5, 2013",2020-07-16 23:21:50,0,0,0
3,My CookBook Ad-Free,0,4.7,2531.0,10.0,0,5.99,9.0,"Sep 25, 2011",2020-07-07 12:41:28,0,0,0
4,Talabat: Food & Grocery Delivery,0,4.4,197649.0,5000.0,1,0.00,9.0,"Jan 19, 2012",2020-07-15 19:21:16,1,0,0

In [89]:
data1.columns

Index(['App Name', 'Category', 'Rating', 'Rating Count(k)', 'Installs(k)',
       'Free', 'Price', 'Size(M)', 'Released', 'Last Updated', 'Ad Supported',
       'In App Purchases', 'Editors Choice'],
      dtype='object')

In [90]:
data2 = data1[['Category', 'Rating', 'Rating Count(k)', 'Installs(k)', 'Free',
       'Price', 'Size(M)', 'Ad Supported',
       'In App Purchases', 'Editors Choice']]

In [91]:
data2.head()

,Category,Rating,Rating Count(k),Installs(k),Free,Price,Size(M),Ad Supported,In App Purchases,Editors Choice
0,0,4.4,1258493.0,10000.0,1,0.00,21.0,0,0,0
1,1,4.4,1360172.0,100000.0,1,0.00,9.0,1,0,0
2,2,4.2,5532.0,500.0,1,0.00,12.0,0,0,0
3,0,4.7,2531.0,10.0,0,5.99,9.0,0,0,0
4,0,4.4,197649.0,5000.0,1,0.00,9.0,1,0,0

#### Music 이랑 Music & Audio랑 합칠 것인지...  -> 나중에

In [92]:
import numpy as np
from sklearn.model_selection import train_test_split

In [93]:
features = ['Category', 'Rating Count(k)',
       'Installs(k)', 'Free', 'Price', 'Size(M)',
       'Ad Supported', 'In App Purchases', 'Editors Choice']
x = data2[features]
y = data2['Rating']

In [94]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 30)

In [95]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

In [96]:
for i in range(5,20):
    model = KNeighborsRegressor(n_neighbors=i)
    model.fit(X_train, y_train)
    accuracy = model.score(X_test,y_test)
    print('neighbors',i,'Accuracy: ' + str(np.round(accuracy*100, 2)) + '%')

neighbors 5 Accuracy: 91.97%
neighbors 6 Accuracy: 92.15%
neighbors 7 Accuracy: 92.28%
neighbors 8 Accuracy: 92.37%
neighbors 9 Accuracy: 92.45%
neighbors 10 Accuracy: 92.51%
neighbors 11 Accuracy: 92.55%
neighbors 12 Accuracy: 92.58%
neighbors 13 Accuracy: 92.61%
neighbors 14 Accuracy: 92.63%
neighbors 15 Accuracy: 92.65%
neighbors 16 Accuracy: 92.67%
neighbors 17 Accuracy: 92.68%
neighbors 18 Accuracy: 92.7%
neighbors 19 Accuracy: 92.71%

In [97]:
model = KNeighborsRegressor(n_neighbors=11)
model.fit(X_train, y_train)
accuracy = model.score(X_test,y_test)

### 적절한 k가 뭔가..

### 거리 척도의 단위 문제 - 표준화(유클리드 거리)
k-NN에서 가깝다는 개념은 유클리드 거리로 정의하는데, ...
어쨋든 k-NN 알고리즘을 적용할 때는 데이터에 표준화가 필요하다는 것이다.

In [107]:
test = pd.read_csv('webapp_test_feature.csv')

In [108]:
test.head()

,App Name,App Id,Category,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,Currency,...,Developer Id,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice
0,Earth & Moon in HD Gyro 3D Parallax Live Wallp...,com.afkettler.earth,Personalization,73806.0,"5,000,000+",5000000.0,7209120,True,0.0,USD,...,CodeKonditor,https://www.facebook.com/codekonditor,mail@codekonditor.com,"Nov 10, 2013",2020-03-21 18:49:16,Everyone,http://www.codekonditor.com/privacy/,False,False,False
1,TakeLessons Live,com.takelessons.tma_android,Education,227.0,"10,000+",10000.0,36956,True,0.0,USD,...,TakeLessons,https://www.takelessons.com,info@takelessons.com,"Oct 5, 2016",2020-07-10 20:59:19,Everyone,https://takelessons.com/privacy,False,False,False
2,Taxi Driving Simulation Be Quick in the City,com.ozGames.taxiDrivingSimulatorDriftPro,Simulation,33.0,"1,000+",1000.0,1251,True,0.0,USD,...,ayris soft,https://ayrissoft.github.io/,hakansatilmis@gmail.com,"Apr 30, 2020",2020-05-01 16:59:24,Teen,https://justpaste.it/27fzs,True,False,False
3,دیکشنری انگلیسی به فارسی آلفا,ir.alphasoft.dictionary,Education,34.0,"1,000+",1000.0,1163,True,0.0,USD,...,Digi.Soft,http://digivpn.xyz,digi.vpn.com@gmail.com,"Mar 10, 2019",2019-03-11 13:58:28,Everyone,http://www.movinapp.com/apps-privacy-policy/,True,False,False
4,Biblia de Jerusalén / Biblia Católica,com.appslitedesarrolladores.bibliadejerusalen,Books & Reference,98.0,"10,000+",10000.0,41051,True,0.0,USD,...,Apps Free Lite,https://appsfreelite.blogspot.com/,appsfreelite@gmail.com,"Oct 22, 2018",2020-04-09 10:35:46,Teen,https://docs.google.com/document/d/e/2PACX-1vQ...,True,False,False

In [109]:
test = test[['App Name', 'Category', 'Rating Count', 'Installs', 'Free', 'Price', 'Size', 'Released', 'Last Updated', 'Ad Supported', 'In App Purchases', 'Editors Choice']]
values = {'Rating Count': test['Rating Count'].median()}
test = test.fillna(value=values)

def to_float(row):
    row = row.rstrip('+').replace(',','')
    return float(row)/1000

test['Installs'] = test['Installs'].apply(to_float)
test = test.rename(columns={'Installs':'Installs(k)'})
test['Size'][test['Size']=='Varies with device'] = np.nan

def k_to_m(row):
    row = str(row).replace(',','')
    if row[-1] == 'k':
        row = float(row[:-1])/1000
    elif row[-1] == 'M':
        row = row[:-1]
    return float(row)  
test['Size'] = test['Size'].apply(k_to_m)
test = test.rename(columns={'Size':'Size(M)'})
test['Size(M)'] = test['Size(M)'].fillna(test['Size(M)'].median())
category_li = test['Category'].unique().tolist()
category_dict = {}
for index, category in enumerate(category_li):
    category_dict[category] = index
def category_to_float(row):
    row = category_dict[row]
    return row
test['Category'] = test['Category'].apply(category_to_float)
def bool_to_int(row):
    if row:
        row = 1
    else:
        row = 0
    return row
test['Ad Supported'] = test['Ad Supported'].apply(bool_to_int)
test['In App Purchases'] = test['In App Purchases'].apply(bool_to_int)
test['Editors Choice'] = test['Editors Choice'].apply(bool_to_int)
test['Free'] = test['Free'].apply(bool_to_int)
test = test[['Category', 'Rating Count', 'Installs(k)', 'Free',
       'Price', 'Size(M)', 'Ad Supported',
       'In App Purchases', 'Editors Choice']]

<ipython-input-109-e58e85e95cd8>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['Size'][test['Size']=='Varies with device'] = np.nan

In [110]:
res = model.predict(test)

In [111]:
print(res)

[4.28181818 3.94545455 3.54545455 ... 4.2        3.64545455 3.9       ]

In [112]:
import csv

In [113]:
resDF = pd.DataFrame({'Rating': res})
resDF.head()

     Rating
0  4.281818
1  3.945455
2  3.545455
3  4.372727
4  3.954545

In [114]:
resDF.to_csv('submission_60201688.csv')